'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Publisher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_stack_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book-stack_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_stack1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_stack1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_stack5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_stack5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_stack6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_stack6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BOOKSTACKFINAL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BOOKSTACKFINAL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoKufiArabic_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoKufiArabic_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoKufiArabic_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoKufiArabic_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoMono_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoMono_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoNaskhArabic_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoNaskhArabic_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoNaskhArabic_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoNaskhArabic_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoNaskhArabicUI_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoNaskhArabicUI_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoNaskhArabicUI_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoNaskhArabicUI_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_BoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_BoldItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Condensed() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Condensed", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_CondensedBold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_CondensedBold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_CondensedBoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_CondensedBoldItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_CondensedItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_CondensedItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Italic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Italic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Light() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Light", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_LightItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_LightItalic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSans_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSans_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansArabic_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansArabic_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansArabic_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansArabic_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansArabicUI_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansArabicUI_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansArabicUI_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansArabicUI_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansArmenian_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansArmenian_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansArmenian_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansArmenian_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansGeorgian_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansGeorgian_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansGeorgian_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansGeorgian_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansHebrew_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansHebrew_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansHebrew_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansHebrew_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansLao_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansLao_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansLao_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansLao_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSansLisu_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSansLisu_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerif_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerif_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerifArmenian_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerifArmenian_Bold", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NotoSerifArmenian_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NotoSerifArmenian_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
